/**
 * Renovation gesture database, UK pathway.
 * Mode 'simple': macro-gestures shown to the general public.
 * Mode 'detail': variants shown at audit level.
 * Indicative costs 2025, England and Wales, installation included, pounds sterling.
 * applicableWhen uses the shared DSL over Building paths.
 */

import type { RenovationGesture } from '../types';

export const GESTURES_UK: RenovationGesture[] = [
  // ------------------------------------------------------------------ walls
  {
    id: 'cavity_wall_insulation',
    name: 'Cavity wall insulation',
    lot: 'murs',
    mode: 'simple',
    description:
      'Mineral wool or bonded bead injected into the cavity through drilled holes. The cheapest major upgrade on interwar and post-war homes, done in a day. Cost per m² of wall.',
    costPerM2: 25,
    epSavingPct: 0.18,
    gesSavingPct: 0.18,
    dhReductionPct: 0.03,
    applicableWhen: 'envelope.wallInsulation=cavite_vide',
    requiresGestureIds: [],
    regulationRefs: ['great_british_insulation_scheme', 'eco4', 'epc_framework'],
  },
  {
    id: 'ite_murs',
    name: 'External wall insulation',
    lot: 'murs',
    mode: 'simple',
    description:
      'Insulation boards fixed to the outside of solid walls and finished with render or cladding, 90 to 150 mm. Removes thermal bridges and refreshes the facade in the same job. Cost per m² of wall.',
    costPerM2: 115,
    epSavingPct: 0.2,
    gesSavingPct: 0.2,
    dhReductionPct: 0.05,
    applicableWhen: 'envelope.wallInsulation=aucune',
    requiresGestureIds: [],
    regulationRefs: ['eco4', 'epc_framework', 'part_l'],
  },
  {
    id: 'iti_murs',
    name: 'Internal wall insulation',
    lot: 'murs',
    mode: 'simple',
    description:
      'Insulated lining fitted to solid walls from the inside, 60 to 100 mm. Used where the facade cannot change, for example in conservation areas. Loses a few centimetres of room depth per wall. Cost per m² of wall.',
    costPerM2: 70,
    epSavingPct: 0.15,
    gesSavingPct: 0.15,
    dhReductionPct: 0.03,
    applicableWhen: 'envelope.wallInsulation=aucune',
    requiresGestureIds: [],
    regulationRefs: ['eco4', 'epc_framework', 'part_l'],
  },
  {
    id: 'iti_biosourcee',
    name: 'Natural fibre internal lining',
    lot: 'murs',
    mode: 'detail',
    description:
      'Internal lining in wood fibre, hemp or cork board, breathable for solid-walled Victorian stock. Good summer thermal lag and a favourable carbon balance. Cost per m² of wall.',
    costPerM2: 85,
    epSavingPct: 0.15,
    gesSavingPct: 0.16,
    dhReductionPct: 0.06,
    applicableWhen: 'envelope.wallInsulation=aucune',
    requiresGestureIds: [],
    regulationRefs: ['eco4', 'part_l'],
  },

  // ------------------------------------------------------------------ roofs
  {
    id: 'isolation_combles_perdus',
    name: 'Loft insulation top-up',
    lot: 'toiture',
    mode: 'simple',
    description:
      'Mineral wool rolled out between and over the joists to reach 270 mm. The single most cost-effective measure in the stock. Cost per m² of loft floor.',
    costPerM2: 35,
    epSavingPct: 0.12,
    gesSavingPct: 0.12,
    dhReductionPct: 0.08,
    applicableWhen: 'envelope.roofType=inclinee;usage=residential_individual',
    requiresGestureIds: [],
    regulationRefs: ['great_british_insulation_scheme', 'eco4', 'epc_framework'],
  },
  {
    id: 'isolation_rampants',
    name: 'Room-in-roof insulation',
    lot: 'toiture',
    mode: 'simple',
    description:
      'Insulation fitted at rafter level where the loft is a lived-in room, 150 to 250 mm in rigid boards. Cost per m² of sloping roof.',
    costPerM2: 60,
    epSavingPct: 0.12,
    gesSavingPct: 0.12,
    dhReductionPct: 0.1,
    applicableWhen: 'envelope.roofType=inclinee',
    requiresGestureIds: [],
    regulationRefs: ['eco4', 'epc_framework', 'part_l'],
  },
  {
    id: 'isolation_toiture_terrasse',
    name: 'Flat roof insulation',
    lot: 'toiture',
    mode: 'simple',
    description:
      'Warm deck insulation above the structure under a new waterproof layer, 150 to 200 mm. Done from outside, no disruption inside. Strongly cuts summer overheating of the top floor. Cost per m² of roof.',
    costPerM2: 95,
    epSavingPct: 0.15,
    gesSavingPct: 0.15,
    dhReductionPct: 0.1,
    applicableWhen: 'envelope.roofType=terrasse',
    requiresGestureIds: [],
    regulationRefs: ['eco4', 'epc_framework', 'part_l', 'approved_document_o'],
  },
  {
    id: 'cool_roof',
    name: 'Cool roof with high reflectance',
    lot: 'toiture',
    mode: 'detail',
    description:
      'Light-coloured coating or reflective membrane that bounces solar radiation back instead of absorbing it. Effective against summer overheating, with no winter insulation gain. Cost per m² of roof.',
    costPerM2: 40,
    epSavingPct: 0.02,
    gesSavingPct: 0.02,
    dhReductionPct: 0.2,
    applicableWhen: 'envelope.roofType=terrasse',
    requiresGestureIds: [],
    regulationRefs: ['approved_document_o', 'ukhsa_heat_health_plan'],
  },
  {
    id: 'toiture_vegetalisee',
    name: 'Extensive green roof',
    lot: 'toiture',
    mode: 'detail',
    description:
      'Sedum blanket on a light substrate. Retains rainwater, protects the waterproofing and cools the top floor in summer. Requires a structural check. Cost per m² of roof.',
    costPerM2: 110,
    epSavingPct: 0.02,
    gesSavingPct: 0.02,
    dhReductionPct: 0.25,
    applicableWhen: 'envelope.roofType=terrasse',
    requiresGestureIds: [],
    regulationRefs: ['approved_document_o', 'ukhsa_heat_health_plan'],
  },

  // ------------------------------------------------------------------ floor
  {
    id: 'isolation_plancher_bas',
    name: 'Suspended timber floor insulation',
    lot: 'plancher',
    mode: 'simple',
    description:
      'Insulation fitted between the joists of a suspended timber ground floor, from below or by lifting boards. Removes draughts and the cold-floor feeling in older homes. Cost per m² of floor.',
    costPerM2: 55,
    epSavingPct: 0.08,
    gesSavingPct: 0.08,
    dhReductionPct: 0.02,
    applicableWhen: '',
    requiresGestureIds: [],
    regulationRefs: ['eco4', 'epc_framework'],
  },

  // --------------------------------------------------------------- windows
  {
    id: 'double_vitrage',
    name: 'High-performance double glazing',
    lot: 'baies',
    mode: 'simple',
    description:
      'uPVC or timber frames with low-emissivity argon-filled double glazing and trickle vents. Ends the cold-window feeling and cuts street noise. Cost per m² of window.',
    costPerM2: 550,
    epSavingPct: 0.12,
    gesSavingPct: 0.12,
    dhReductionPct: 0.05,
    applicableWhen: 'envelope.glazingType=simple',
    requiresGestureIds: [],
    regulationRefs: ['epc_framework', 'part_l'],
  },
  {
    id: 'renouvellement_double_vitrage',
    name: 'Replacement of early double glazing',
    lot: 'baies',
    mode: 'detail',
    description:
      'Swap of first-generation double glazing for modern low-emissivity argon units, with airtightness work around the frames. Cost per m² of window.',
    costPerM2: 500,
    epSavingPct: 0.06,
    gesSavingPct: 0.06,
    dhReductionPct: 0.03,
    applicableWhen: 'envelope.glazingType=double',
    requiresGestureIds: [],
    regulationRefs: ['epc_framework', 'part_l'],
  },
  {
    id: 'triple_vitrage',
    name: 'Triple glazing on exposed facades',
    lot: 'baies',
    mode: 'detail',
    description:
      'Low-emissivity triple glazing on north and east facing walls. Reserved for cold regions and deep-retrofit projects. Cost per m² of window.',
    costPerM2: 680,
    epSavingPct: 0.1,
    gesSavingPct: 0.1,
    dhReductionPct: 0.04,
    applicableWhen: 'envelope.glazingType!=triple',
    requiresGestureIds: [],
    regulationRefs: ['part_l', 'future_homes_standard'],
  },

  // -------------------------------------------------- solar shading
  {
    id: 'protections_solaires_exterieures',
    name: 'External blinds or shutters',
    lot: 'protections_solaires',
    mode: 'simple',
    description:
      'External venetian blinds, awnings or shutters fitted outside the glass. Block the sun before it heats the glazing: the most effective anti-overheating measure. Cost per m² of equipped window.',
    costPerM2: 230,
    epSavingPct: 0.03,
    gesSavingPct: 0.03,
    dhReductionPct: 0.28,
    applicableWhen: 'envelope.solarProtection=false',
    requiresGestureIds: [],
    regulationRefs: ['approved_document_o', 'ukhsa_heat_health_plan'],
  },
  {
    id: 'volets_roulants_isolants',
    name: 'Motorised insulated roller shutters',
    lot: 'protections_solaires',
    mode: 'detail',
    description:
      'Insulated roller shutters with motor and timer. Closed by day in summer they cut overheating; closed at night in winter they add thermal resistance. Cost per m² of equipped window.',
    costPerM2: 190,
    epSavingPct: 0.03,
    gesSavingPct: 0.03,
    dhReductionPct: 0.22,
    applicableWhen: 'envelope.solarProtection=false',
    requiresGestureIds: [],
    regulationRefs: ['approved_document_o', 'ukhsa_heat_health_plan'],
  },
  {
    id: 'brise_soleil_fixe',
    name: 'Fixed solar shading on south and west facades',
    lot: 'protections_solaires',
    mode: 'detail',
    description:
      'Horizontal canopy sized to block high summer sun and admit low winter sun. Maintenance-free, suited to offices and schools. Cost per m² of shaded window.',
    costPerM2: 280,
    epSavingPct: 0.02,
    gesSavingPct: 0.02,
    dhReductionPct: 0.25,
    applicableWhen: 'envelope.solarProtection=false',
    requiresGestureIds: [],
    regulationRefs: ['approved_document_o', 'part_l'],
  },
  {
    id: 'films_solaires',
    name: 'Solar control films on exposed glazing',
    lot: 'protections_solaires',
    mode: 'detail',
    description:
      'Reflective adhesive films applied to south and west glazing. Quick and cheap, less effective than external shading and to be renewed every ten years or so. Cost per m² of treated glass.',
    costPerM2: 55,
    epSavingPct: 0.01,
    gesSavingPct: 0.01,
    dhReductionPct: 0.15,
    applicableWhen: 'envelope.solarProtection=false',
    requiresGestureIds: [],
    regulationRefs: ['ukhsa_heat_health_plan'],
  },

  // --------------------------------------------------------------- heating
  {
    id: 'pac_air_eau',
    name: 'Air source heat pump',
    lot: 'chauffage',
    mode: 'simple',
    description:
      'Replacement of the boiler by an air source heat pump connected to the existing emitters. Cuts heating energy by two to three and takes the home off fossil fuels. Fixed part plus capacity pricing per kW installed.',
    // Capacity pricing: the engine computes fixedCost + kW x price per kW,
    // with capacity sized on the building (see scenarios.ts).
    fixedCost: 10500,
    epSavingPct: 0.5,
    gesSavingPct: 0.75,
    dhReductionPct: 0,
    applicableWhen: 'systems.heating.energy!=pac',
    requiresGestureIds: ['emetteurs_basse_temperature'],
    regulationRefs: ['boiler_upgrade_scheme', 'eco4', 'epc_framework', 'future_homes_standard'],
  },
  {
    id: 'pac_air_air',
    name: 'Reversible air-to-air heat pump',
    lot: 'chauffage',
    mode: 'detail',
    description:
      'Wall-mounted indoor units that heat in winter and cool in summer. A good replacement for panel or storage heaters. Fixed part per home plus capacity pricing per kW installed.',
    // Capacity pricing: the engine computes fixedCost + kW x price per kW,
    // with capacity sized on the building (see scenarios.ts).
    fixedCost: 4000,
    epSavingPct: 0.4,
    gesSavingPct: 0.7,
    dhReductionPct: 0.3,
    applicableWhen: 'systems.heating.energy!=pac;systems.cooling=null',
    requiresGestureIds: [],
    regulationRefs: ['epc_framework', 'ukhsa_heat_health_plan'],
  },
  {
    id: 'chaudiere_gaz_thpe',
    name: 'New condensing combi boiler',
    lot: 'chauffage',
    mode: 'detail',
    description:
      'Replacement of an old boiler by a modern condensing combi. A real but limited gain: the home stays on fossil gas. Fixed price, installation included.',
    fixedCost: 2800,
    epSavingPct: 0.12,
    gesSavingPct: 0.12,
    dhReductionPct: 0,
    applicableWhen: 'systems.heating.energy=gaz_naturel',
    requiresGestureIds: [],
    regulationRefs: ['epc_framework'],
  },
  {
    id: 'storage_heater_replacement',
    name: 'High heat retention storage heaters',
    lot: 'chauffage',
    mode: 'detail',
    description:
      'Replacement of old night storage heaters by high heat retention models with precise charge control. Improves comfort and cuts wasted heat, while staying electric. Fixed price for the home.',
    fixedCost: 4000,
    epSavingPct: 0.12,
    gesSavingPct: 0.1,
    dhReductionPct: 0,
    applicableWhen: 'systems.heating.energy=electricite',
    requiresGestureIds: [],
    regulationRefs: ['eco4', 'epc_framework'],
  },
  {
    id: 'raccordement_reseau_chaleur',
    name: 'District heat network connection',
    lot: 'chauffage',
    mode: 'detail',
    description:
      'Replacement of the plant room by a connection to a local heat network, where one passes nearby. Strong carbon savings when the network runs on waste heat or low-carbon sources. Fixed price with substation.',
    fixedCost: 7500,
    epSavingPct: 0.2,
    gesSavingPct: 0.5,
    dhReductionPct: 0,
    applicableWhen: 'systems.heating.energy!=reseau_chaleur;usage!=residential_individual',
    requiresGestureIds: [],
    regulationRefs: ['epc_framework', 'future_homes_standard'],
  },
  {
    id: 'emetteurs_basse_temperature',
    name: 'Low-temperature emitters',
    lot: 'chauffage',
    mode: 'detail',
    description:
      'Oversized radiators or fan convectors sized for a 45 °C flow temperature. The condition for a heat pump to perform well on an existing system. Fixed price for the home.',
    fixedCost: 3200,
    epSavingPct: 0.08,
    gesSavingPct: 0.08,
    dhReductionPct: 0,
    applicableWhen: '',
    requiresGestureIds: [],
    regulationRefs: ['boiler_upgrade_scheme', 'epc_framework'],
  },
  {
    id: 'desembouage_calorifugeage',
    name: 'System flush and pipe insulation',
    lot: 'chauffage',
    mode: 'detail',
    description:
      'Power flush of the heating circuit and insulation of pipes in unheated spaces. Small job, fast payback, a classic prerequisite before any boiler or heat pump swap. Fixed price.',
    fixedCost: 450,
    epSavingPct: 0.04,
    gesSavingPct: 0.04,
    dhReductionPct: 0,
    applicableWhen: 'systems.heating.energy!=electricite',
    requiresGestureIds: [],
    regulationRefs: ['part_l'],
  },

  // ------------------------------------------------------------------- DHW
  {
    id: 'chauffe_eau_thermodynamique',
    name: 'Heat pump hot water cylinder',
    lot: 'ecs',
    mode: 'simple',
    description:
      'Hot water produced by a heat pump cylinder drawing on indoor or outdoor air. Uses two to three times less electricity than a standard immersion heater. Fixed price, installation included.',
    fixedCost: 2600,
    epSavingPct: 0.08,
    gesSavingPct: 0.1,
    dhReductionPct: 0,
    applicableWhen: '',
    requiresGestureIds: [],
    regulationRefs: ['epc_framework', 'part_l'],
  },
  {
    id: 'solaire_thermique',
    name: 'Solar thermal hot water',
    lot: 'ecs',
    mode: 'detail',
    description:
      'Roof collectors feeding a twin-coil cylinder. Covers 40 to 60 % of annual hot water demand, with the existing system as backup. Fixed price, installation included.',
    fixedCost: 4800,
    epSavingPct: 0.06,
    gesSavingPct: 0.08,
    dhReductionPct: 0,
    applicableWhen: '',
    requiresGestureIds: [],
    regulationRefs: ['epc_framework', 'part_l'],
  },

  // --------------------------------------------------------- cooling
  {
    id: 'brasseurs_air',
    name: 'Ceiling fans',
    lot: 'refroidissement',
    mode: 'simple',
    description:
      'Ceiling fans in living rooms and bedrooms. Moving air improves the felt temperature by 2 to 3 °C without air conditioning. Fixed price for a home or an office floor.',
    fixedCost: 500,
    epSavingPct: 0.02,
    gesSavingPct: 0.02,
    dhReductionPct: 0.2,
    applicableWhen: 'systems.hasCeilingFans=false',
    requiresGestureIds: [],
    regulationRefs: ['ukhsa_heat_health_plan'],
  },
  {
    id: 'surventilation_nocturne',
    name: 'Mechanical night purge ventilation',
    lot: 'refroidissement',
    mode: 'detail',
    description:
      'Forced ventilation driven at night to dump the heat stored in walls and floors. Effective on medium and heavy construction. Fixed price with fans and controls.',
    fixedCost: 2200,
    epSavingPct: 0.01,
    gesSavingPct: 0.01,
    dhReductionPct: 0.25,
    applicableWhen: 'systems.cooling=null;envelope.inertia!=legere',
    requiresGestureIds: [],
    regulationRefs: ['approved_document_o', 'ukhsa_heat_health_plan'],
  },

  // ------------------------------------------------------------ ventilation
  {
    id: 'vmc_double_flux',
    name: 'Mechanical ventilation with heat recovery',
    lot: 'ventilation',
    mode: 'simple',
    description:
      'Heat recovery on extracted air with filtered fresh air. The summer bypass lets the system over-ventilate at night during hot spells. Fixed price, installation included.',
    fixedCost: 4200,
    epSavingPct: 0.1,
    gesSavingPct: 0.1,
    dhReductionPct: 0.1,
    applicableWhen: 'systems.ventilation!=vmc_double_flux',
    requiresGestureIds: [],
    regulationRefs: ['eco4', 'epc_framework', 'part_l', 'approved_document_o'],
  },
  {
    id: 'vmc_hygro_b',
    name: 'Demand-controlled extract ventilation',
    lot: 'ventilation',
    mode: 'detail',
    description:
      'Extract units and air inlets that modulate airflow with humidity and occupancy. Cuts ventilation heat loss without degrading air quality. Fixed price, installation included.',
    fixedCost: 900,
    epSavingPct: 0.06,
    gesSavingPct: 0.06,
    dhReductionPct: 0.02,
    applicableWhen: 'systems.ventilation=naturelle',
    requiresGestureIds: [],
    regulationRefs: ['epc_framework', 'part_l'],
  },

  // ----------------------------------------------------------------- solar
  {
    id: 'pv_autoconsommation',
    name: 'Rooftop solar PV for self-consumption',
    lot: 'solaire',
    mode: 'simple',
    description:
      'Solar array sized on daytime usage. Cuts electricity bought from the grid and associated emissions, with export paid under the Smart Export Guarantee. Cost per m² of installed panel.',
    costPerM2: 230,
    epSavingPct: 0.07,
    gesSavingPct: 0.05,
    dhReductionPct: 0,
    applicableWhen: 'systems.pvSurfaceM2<10',
    requiresGestureIds: [],
    regulationRefs: ['epc_framework', 'future_homes_standard'],
  },
  {
    id: 'pv_extension',
    name: 'Extension of the existing solar array',
    lot: 'solaire',
    mode: 'detail',
    description:
      'Additional panels on the free roof slopes, with the inverter resized. Cost per m² of installed panel.',
    costPerM2: 210,
    epSavingPct: 0.04,
    gesSavingPct: 0.03,
    dhReductionPct: 0,
    applicableWhen: 'systems.pvSurfaceM2>10',
    requiresGestureIds: [],
    regulationRefs: ['epc_framework'],
  },

  // ------------------------------------------------------------------ usage
  {
    id: 'thermostat_programmation',
    name: 'Smart heating controls',
    lot: 'usage',
    mode: 'simple',
    description:
      'Smart thermostat, programmers and thermostatic radiator valves, room by room. Cheap measure with an immediate payback. Fixed price.',
    fixedCost: 300,
    epSavingPct: 0.08,
    gesSavingPct: 0.08,
    dhReductionPct: 0,
    applicableWhen: '',
    requiresGestureIds: [],
    regulationRefs: ['part_l', 'epc_framework'],
  },
  {
    id: 'draught_proofing',
    name: 'Draught proofing',
    lot: 'usage',
    mode: 'detail',
    description:
      'Sealing of gaps around windows, doors, loft hatches, floorboards and letterboxes. Cheap, quick, and it makes every other measure work better. Fixed price.',
    fixedCost: 250,
    epSavingPct: 0.05,
    gesSavingPct: 0.05,
    dhReductionPct: 0.02,
    applicableWhen: '',
    requiresGestureIds: [],
    regulationRefs: ['epc_framework'],
  },
];
