/**
 * Base de gestes de rénovation, parcours France.
 * Mode 'simple' : macrogestes présentés au grand public.
 * Mode 'detail' : variantes affichées au niveau audit.
 * Coûts indicatifs 2025, France continentale, pose comprise, euros TTC.
 * applicableWhen utilise le DSL partagé sur les chemins de Building.
 */

import type { RenovationGesture } from '../types';

export const GESTURES_FR: RenovationGesture[] = [
  // ------------------------------------------------------------------ murs
  {
    id: 'ite_murs',
    name: 'Isolation thermique par l’extérieur',
    lot: 'murs',
    mode: 'simple',
    description:
      'Pose d’un isolant en façade sous enduit ou bardage, 14 à 20 cm. Supprime les ponts thermiques et rénove l’aspect de la façade dans le même chantier. Coût par m² de mur.',
    costPerM2: 120,
    epSavingPct: 0.2,
    gesSavingPct: 0.2,
    dhReductionPct: 0.05,
    applicableWhen: 'envelope.wallInsulation=aucune',
    requiresGestureIds: [],
    regulationRefs: ['maprimenov', 'cee', 'dpe_2021', 'interdiction_location'],
  },
  {
    id: 'iti_murs',
    name: 'Isolation thermique par l’intérieur',
    lot: 'murs',
    mode: 'simple',
    description:
      'Doublage isolant des murs depuis l’intérieur, 10 à 14 cm. Solution retenue quand la façade ne peut pas être modifiée. Perte de surface habitable de quelques centimètres par mur. Coût par m² de mur.',
    costPerM2: 70,
    epSavingPct: 0.15,
    gesSavingPct: 0.15,
    dhReductionPct: 0.03,
    applicableWhen: 'envelope.wallInsulation=aucune',
    requiresGestureIds: [],
    regulationRefs: ['maprimenov', 'cee', 'dpe_2021'],
  },
  {
    id: 'iti_biosourcee',
    name: 'Doublage intérieur en isolant biosourcé',
    lot: 'murs',
    mode: 'detail',
    description:
      'Variante du doublage intérieur en fibre de bois, laine de chanvre ou ouate de cellulose. Bon déphasage thermique en été et bilan carbone favorable. Coût par m² de mur.',
    costPerM2: 90,
    epSavingPct: 0.15,
    gesSavingPct: 0.16,
    dhReductionPct: 0.06,
    applicableWhen: 'envelope.wallInsulation=aucune',
    requiresGestureIds: [],
    regulationRefs: ['maprimenov', 'cee', 're2020'],
  },
  {
    id: 'renfort_ite',
    name: 'Renfort d’isolation sur façade déjà isolée par l’intérieur',
    lot: 'murs',
    mode: 'detail',
    description:
      'Sur une façade déjà doublée par l’intérieur, ajout d’une isolation extérieure mince lors d’un ravalement. Complète l’isolation sans toucher aux pièces habitées. Coût par m² de mur.',
    costPerM2: 90,
    epSavingPct: 0.08,
    gesSavingPct: 0.08,
    dhReductionPct: 0.04,
    applicableWhen: 'envelope.wallInsulation=iti',
    requiresGestureIds: [],
    regulationRefs: ['cee', 'dpe_2021'],
  },

  // ---------------------------------------------------------------- toiture
  {
    id: 'isolation_toiture_terrasse',
    name: 'Isolation de la toiture terrasse par l’extérieur',
    lot: 'toiture',
    mode: 'simple',
    description:
      'Sarking ou isolation sous étanchéité, 16 à 24 cm. Chantier réalisé depuis l’extérieur, sans déranger les occupants. Réduit fortement la surchauffe du dernier niveau en été. Coût par m² de toiture.',
    costPerM2: 90,
    epSavingPct: 0.15,
    gesSavingPct: 0.15,
    dhReductionPct: 0.1,
    applicableWhen: 'envelope.roofType=terrasse',
    requiresGestureIds: [],
    regulationRefs: ['maprimenov', 'cee', 'dpe_2021', 're2020'],
  },
  {
    id: 'isolation_rampants',
    name: 'Isolation des rampants de toiture',
    lot: 'toiture',
    mode: 'simple',
    description:
      'Isolation sous pente pour les combles aménagés ou à aménager, 24 à 30 cm en deux couches croisées. Coût par m² de rampant.',
    costPerM2: 60,
    epSavingPct: 0.12,
    gesSavingPct: 0.12,
    dhReductionPct: 0.1,
    applicableWhen: 'envelope.roofType=inclinee',
    requiresGestureIds: [],
    regulationRefs: ['maprimenov', 'cee', 'dpe_2021'],
  },
  {
    id: 'isolation_combles_perdus',
    name: 'Soufflage d’isolant en combles perdus',
    lot: 'toiture',
    mode: 'detail',
    description:
      'Soufflage de ouate de cellulose ou de laine minérale sur le plancher des combles, 30 à 40 cm. Geste le moins cher et le plus rentable du parcours. Coût par m² de plancher de comble.',
    costPerM2: 35,
    epSavingPct: 0.1,
    gesSavingPct: 0.1,
    dhReductionPct: 0.08,
    applicableWhen: 'envelope.roofType=inclinee;usage=residential_individual',
    requiresGestureIds: [],
    regulationRefs: ['maprimenov', 'cee', 'dpe_2021'],
  },
  {
    id: 'cool_roof',
    name: 'Toiture fraîche à forte réflectance',
    lot: 'toiture',
    mode: 'detail',
    description:
      'Revetement clair ou membrane réfléchissante qui renvoie le rayonnement solaire au lieu de l’absorber. Efficace contre la surchauffe estivale, sans gain d’isolation hivernale. Coût par m² de toiture.',
    costPerM2: 40,
    epSavingPct: 0.02,
    gesSavingPct: 0.02,
    dhReductionPct: 0.2,
    applicableWhen: 'envelope.roofType=terrasse',
    requiresGestureIds: [],
    regulationRefs: ['re2020', 'plan_canicule'],
  },
  {
    id: 'toiture_vegetalisee',
    name: 'Végétalisation extensive de la toiture',
    lot: 'toiture',
    mode: 'detail',
    description:
      'Couche de sedums sur substrat léger. Retient l’eau de pluie, protège l’étanchéité et tempère le dernier niveau en été. Nécessite une vérification de la structure porteuse. Coût par m² de toiture.',
    costPerM2: 120,
    epSavingPct: 0.02,
    gesSavingPct: 0.02,
    dhReductionPct: 0.25,
    applicableWhen: 'envelope.roofType=terrasse',
    requiresGestureIds: [],
    regulationRefs: ['re2020', 'plan_canicule'],
  },

  // --------------------------------------------------------------- plancher
  {
    id: 'isolation_plancher_bas',
    name: 'Isolation du plancher bas',
    lot: 'plancher',
    mode: 'simple',
    description:
      'Isolation du plancher sur vide sanitaire, cave ou terre-plein, en sous-face ou par le dessus. Améliore le confort d’hiver et supprime la sensation de sol froid. Coût par m² de plancher.',
    costPerM2: 65,
    epSavingPct: 0.08,
    gesSavingPct: 0.08,
    dhReductionPct: 0.02,
    applicableWhen: '',
    requiresGestureIds: [],
    regulationRefs: ['maprimenov', 'cee', 'dpe_2021'],
  },

  // ------------------------------------------------------------------ baies
  {
    id: 'double_vitrage',
    name: 'Remplacement des fenêtres par du double vitrage performant',
    lot: 'baies',
    mode: 'simple',
    description:
      'Menuiseries PVC ou bois avec double vitrage à isolation renforcée et entrées d’air hygroréglables. Supprime la sensation de paroi froide et réduit le bruit. Coût par m² de baie.',
    costPerM2: 600,
    epSavingPct: 0.12,
    gesSavingPct: 0.12,
    dhReductionPct: 0.05,
    applicableWhen: 'envelope.glazingType=simple',
    requiresGestureIds: [],
    regulationRefs: ['maprimenov', 'cee', 'dpe_2021'],
  },
  {
    id: 'renouvellement_double_vitrage',
    name: 'Renouvellement des menuiseries à double vitrage ancien',
    lot: 'baies',
    mode: 'detail',
    description:
      'Remplacement de doubles vitrages de première génération par des vitrages faiblement émissifs à gaz argon, avec reprise de l’étanchéité à l’air en périphérie. Coût par m² de baie.',
    costPerM2: 550,
    epSavingPct: 0.06,
    gesSavingPct: 0.06,
    dhReductionPct: 0.03,
    applicableWhen: 'envelope.glazingType=double',
    requiresGestureIds: [],
    regulationRefs: ['cee', 'dpe_2021'],
  },
  {
    id: 'triple_vitrage',
    name: 'Triple vitrage sur les façades exposées',
    lot: 'baies',
    mode: 'detail',
    description:
      'Triple vitrage à faible émissivité sur les façades nord et est. À réserver aux climats froids et aux projets visant une très haute performance. Coût par m² de baie.',
    costPerM2: 750,
    epSavingPct: 0.1,
    gesSavingPct: 0.1,
    dhReductionPct: 0.04,
    applicableWhen: 'envelope.glazingType!=triple',
    requiresGestureIds: [],
    regulationRefs: ['cee', 'dpe_2021', 're2020'],
  },

  // -------------------------------------------------- protections solaires
  {
    id: 'protections_solaires_exterieures',
    name: 'Protections solaires extérieures mobiles',
    lot: 'protections_solaires',
    mode: 'simple',
    description:
      'Stores, brise-soleil orientables ou volets battants posés en extérieur des baies. Bloque le rayonnement avant qu’il ne chauffe le vitrage : le geste le plus efficace contre la surchauffe. Coût par m² de baie équipée.',
    costPerM2: 250,
    epSavingPct: 0.03,
    gesSavingPct: 0.03,
    dhReductionPct: 0.28,
    applicableWhen: 'envelope.solarProtection=false',
    requiresGestureIds: [],
    regulationRefs: ['re2020', 'plan_canicule', 'maprimenov'],
  },
  {
    id: 'volets_roulants_isolants',
    name: 'Volets roulants isolants motorisés',
    lot: 'protections_solaires',
    mode: 'detail',
    description:
      'Volets roulants à lames isolées avec motorisation et pilotage horaire. Fermés le jour en été, ils limitent la surchauffe ; fermés la nuit en hiver, ils ajoutent une résistance thermique. Coût par m² de baie équipée.',
    costPerM2: 200,
    epSavingPct: 0.03,
    gesSavingPct: 0.03,
    dhReductionPct: 0.22,
    applicableWhen: 'envelope.solarProtection=false',
    requiresGestureIds: [],
    regulationRefs: ['re2020', 'plan_canicule'],
  },
  {
    id: 'brise_soleil_fixe',
    name: 'Brise-soleil fixe ou casquette sur façades sud et ouest',
    lot: 'protections_solaires',
    mode: 'detail',
    description:
      'Casquette horizontale dimensionnée pour masquer le soleil d’été et laisser passer le soleil d’hiver. Solution sans entretien, adaptée aux façades tertiaires. Coût par m² de baie protégée.',
    costPerM2: 300,
    epSavingPct: 0.02,
    gesSavingPct: 0.02,
    dhReductionPct: 0.25,
    applicableWhen: 'envelope.solarProtection=false',
    requiresGestureIds: [],
    regulationRefs: ['re2020', 'plan_canicule', 'decret_tertiaire'],
  },
  {
    id: 'films_solaires',
    name: 'Films solaires sur vitrages exposés',
    lot: 'protections_solaires',
    mode: 'detail',
    description:
      'Films adhésifs réfléchissants posés sur les vitrages sud et ouest. Solution rapide et peu coûteuse, moins efficace qu’une protection extérieure et à renouveler tous les dix ans environ. Coût par m² de vitrage traité.',
    costPerM2: 60,
    epSavingPct: 0.01,
    gesSavingPct: 0.01,
    dhReductionPct: 0.15,
    applicableWhen: 'envelope.solarProtection=false',
    requiresGestureIds: [],
    regulationRefs: ['plan_canicule'],
  },

  // -------------------------------------------------------------- chauffage
  {
    id: 'pac_air_eau',
    name: 'Pompe à chaleur air/eau',
    lot: 'chauffage',
    mode: 'simple',
    description:
      'Remplacement du générateur par une pompe à chaleur air/eau raccordée sur l’émetteur existant. Divise par deux à trois la consommation de chauffage et sort le bâtiment des énergies fossiles. Forfait pose comprise.',
    fixedCost: 12000,
    epSavingPct: 0.5,
    gesSavingPct: 0.75,
    dhReductionPct: 0,
    applicableWhen: 'systems.heating.energy!=pac',
    requiresGestureIds: ['emetteurs_basse_temperature'],
    regulationRefs: ['maprimenov', 'cee', 'dpe_2021', 'interdiction_location'],
  },
  {
    id: 'pac_air_air',
    name: 'Pompe à chaleur air/air réversible',
    lot: 'chauffage',
    mode: 'detail',
    description:
      'Unités intérieures murales qui chauffent l’hiver et rafraîchissent l’été. Pertinente en remplacement de convecteurs électriques. Coût par m² de surface habitable.',
    costPerM2: 95,
    epSavingPct: 0.4,
    gesSavingPct: 0.7,
    dhReductionPct: 0.3,
    applicableWhen: 'systems.heating.energy!=pac;systems.cooling=null',
    requiresGestureIds: [],
    regulationRefs: ['cee', 'dpe_2021', 'plan_canicule'],
  },
  {
    id: 'chaudiere_gaz_thpe',
    name: 'Chaudière gaz à très haute performance énergétique',
    lot: 'chauffage',
    mode: 'detail',
    description:
      'Remplacement d’une vieille chaudière gaz par un modèle à condensation. Gain réel mais limité : ce geste maintient le bâtiment au gaz fossile et n’est plus subventionné. Forfait pose comprise.',
    fixedCost: 5500,
    epSavingPct: 0.12,
    gesSavingPct: 0.12,
    dhReductionPct: 0,
    applicableWhen: 'systems.heating.energy=gaz_naturel',
    requiresGestureIds: [],
    regulationRefs: ['dpe_2021'],
  },
  {
    id: 'chaudiere_granules',
    name: 'Chaudière à granulés de bois',
    lot: 'chauffage',
    mode: 'detail',
    description:
      'Chaudière automatique à granulés avec silo de stockage. Combustible renouvelable et stable en prix, pertinent en zone rurale hors réseau de gaz. Forfait avec silo.',
    fixedCost: 14000,
    epSavingPct: 0.1,
    gesSavingPct: 0.8,
    dhReductionPct: 0,
    applicableWhen: 'systems.heating.energy!=bois;usage=residential_individual',
    requiresGestureIds: [],
    regulationRefs: ['maprimenov', 'cee', 'dpe_2021'],
  },
  {
    id: 'raccordement_reseau_chaleur',
    name: 'Raccordement à un réseau de chaleur',
    lot: 'chauffage',
    mode: 'detail',
    description:
      'Substitution de la chaufferie par un raccordement au réseau de chaleur urbain, quand il passe à proximité. Réduit fortement les émissions quand le réseau est alimenté par des énergies renouvelables ou de récupération. Forfait avec sous-station.',
    fixedCost: 8000,
    epSavingPct: 0.2,
    gesSavingPct: 0.5,
    dhReductionPct: 0,
    applicableWhen: 'systems.heating.energy!=reseau_chaleur;usage!=residential_individual',
    requiresGestureIds: [],
    regulationRefs: ['cee', 'dpe_2021', 'decret_tertiaire'],
  },
  {
    id: 'emetteurs_basse_temperature',
    name: 'Émetteurs basse température',
    lot: 'chauffage',
    mode: 'detail',
    description:
      'Radiateurs basse température ou ventilo-convecteurs dimensionnés pour un régime d’eau à 45 °C. Condition de bon fonctionnement d’une pompe à chaleur sur installation existante. Forfait pour le logement.',
    fixedCost: 3500,
    epSavingPct: 0.08,
    gesSavingPct: 0.08,
    dhReductionPct: 0,
    applicableWhen: '',
    requiresGestureIds: [],
    regulationRefs: ['cee', 'dpe_2021'],
  },
  {
    id: 'desembouage_calorifugeage',
    name: 'Desembouage et calorifugeage du réseau hydraulique',
    lot: 'chauffage',
    mode: 'detail',
    description:
      'Nettoyage du circuit de chauffage et isolation des tuyaux en zones non chauffées. Petit geste, retour rapide, prérequis classique avant tout remplacement de générateur. Forfait.',
    fixedCost: 900,
    epSavingPct: 0.04,
    gesSavingPct: 0.04,
    dhReductionPct: 0,
    applicableWhen: 'systems.heating.energy!=electricite',
    requiresGestureIds: [],
    regulationRefs: ['cee'],
  },

  // -------------------------------------------------------------------- ecs
  {
    id: 'chauffe_eau_thermodynamique',
    name: 'Chauffe-eau thermodynamique',
    lot: 'ecs',
    mode: 'simple',
    description:
      'Production d’eau chaude sanitaire par pompe à chaleur sur air extrait ou air extérieur. Consomme deux à trois fois moins qu’un ballon électrique classique. Forfait pose comprise.',
    fixedCost: 2800,
    epSavingPct: 0.08,
    gesSavingPct: 0.1,
    dhReductionPct: 0,
    applicableWhen: '',
    requiresGestureIds: [],
    regulationRefs: ['maprimenov', 'cee', 'dpe_2021'],
  },
  {
    id: 'solaire_thermique',
    name: 'Chauffe-eau solaire individuel',
    lot: 'ecs',
    mode: 'detail',
    description:
      'Capteurs en toiture et ballon à double échangeur. Couvre 50 à 70 % des besoins d’eau chaude sur l’année, avec l’appoint existant en relève. Forfait pose comprise.',
    fixedCost: 6000,
    epSavingPct: 0.06,
    gesSavingPct: 0.08,
    dhReductionPct: 0,
    applicableWhen: '',
    requiresGestureIds: [],
    regulationRefs: ['maprimenov', 'cee', 'dpe_2021'],
  },

  // --------------------------------------------------------- refroidissement
  {
    id: 'brasseurs_air',
    name: 'Brasseurs d’air de plafond',
    lot: 'refroidissement',
    mode: 'simple',
    description:
      'Brasseurs de plafond dans les pièces de vie et les chambres. Le flux d’air améliore la sensation de confort de 2 à 3 °C sans climatisation. Forfait pour un logement ou un plateau de bureaux.',
    fixedCost: 800,
    epSavingPct: 0.02,
    gesSavingPct: 0.02,
    dhReductionPct: 0.2,
    applicableWhen: 'systems.hasCeilingFans=false',
    requiresGestureIds: [],
    regulationRefs: ['plan_canicule', 're2020'],
  },
  {
    id: 'surventilation_nocturne',
    name: 'Surventilation nocturne motorisée',
    lot: 'refroidissement',
    mode: 'detail',
    description:
      'Ventilation forcée pilotée la nuit pour décharger la chaleur accumulée dans les parois. Efficace sur les bâtiments à inertie moyenne ou lourde. Forfait avec caissons et régulation.',
    fixedCost: 2500,
    epSavingPct: 0.01,
    gesSavingPct: 0.01,
    dhReductionPct: 0.25,
    applicableWhen: 'systems.cooling=null;envelope.inertia!=legere',
    requiresGestureIds: [],
    regulationRefs: ['re2020', 'plan_canicule'],
  },

  // ------------------------------------------------------------ ventilation
  {
    id: 'vmc_double_flux',
    name: 'Ventilation double flux avec échangeur',
    lot: 'ventilation',
    mode: 'simple',
    description:
      'Récupération de chaleur sur l’air extrait et filtration de l’air neuf. Le bypass d’été permet de surventiler la nuit pendant les épisodes chauds. Forfait pose comprise.',
    fixedCost: 4500,
    epSavingPct: 0.1,
    gesSavingPct: 0.1,
    dhReductionPct: 0.1,
    applicableWhen: 'systems.ventilation!=vmc_double_flux',
    requiresGestureIds: [],
    regulationRefs: ['maprimenov', 'cee', 'dpe_2021', 're2020'],
  },
  {
    id: 'vmc_hygro_b',
    name: 'VMC simple flux hygroréglable de type B',
    lot: 'ventilation',
    mode: 'detail',
    description:
      'Bouches et entrées d’air qui modulent les débits selon l’humidité intérieure. Réduit les déperditions par ventilation sans dégrader la qualité d’air. Forfait pose comprise.',
    fixedCost: 1500,
    epSavingPct: 0.06,
    gesSavingPct: 0.06,
    dhReductionPct: 0.02,
    applicableWhen: 'systems.ventilation=naturelle',
    requiresGestureIds: [],
    regulationRefs: ['cee', 'dpe_2021'],
  },

  // ---------------------------------------------------------------- solaire
  {
    id: 'pv_autoconsommation',
    name: 'Panneaux photovoltaïques en autoconsommation',
    lot: 'solaire',
    mode: 'simple',
    description:
      'Centrale photovoltaïque en toiture dimensionnée sur les usages de jour. Réduit la consommation achetée au réseau et les émissions associées. Coût par m² de panneau posé.',
    costPerM2: 300,
    epSavingPct: 0.07,
    gesSavingPct: 0.05,
    dhReductionPct: 0,
    applicableWhen: 'systems.pvSurfaceM2<10',
    requiresGestureIds: [],
    regulationRefs: ['dpe_2021'],
  },
  {
    id: 'pv_extension',
    name: 'Extension de la centrale photovoltaïque existante',
    lot: 'solaire',
    mode: 'detail',
    description:
      'Ajout de panneaux sur les pans de toiture encore libres, avec reprise du dimensionnement de l’onduleur. Coût par m² de panneau posé.',
    costPerM2: 280,
    epSavingPct: 0.04,
    gesSavingPct: 0.03,
    dhReductionPct: 0,
    applicableWhen: 'systems.pvSurfaceM2>10',
    requiresGestureIds: [],
    regulationRefs: ['dpe_2021'],
  },

  // ------------------------------------------------------------------ usage
  {
    id: 'thermostat_programmation',
    name: 'Thermostat programmable et robinets thermostatiques',
    lot: 'usage',
    mode: 'simple',
    description:
      'Programmation des températures pièce par pièce : 19 °C dans les pièces de vie, abaissement la nuit et en absence. Geste peu coûteux au retour sur investissement immédiat. Forfait.',
    fixedCost: 300,
    epSavingPct: 0.08,
    gesSavingPct: 0.08,
    dhReductionPct: 0,
    applicableWhen: '',
    requiresGestureIds: [],
    regulationRefs: ['cee', 'decret_tertiaire'],
  },
  {
    id: 'eco_gestion_consignes',
    name: 'Charte de gestion des consignes et des usages',
    lot: 'usage',
    mode: 'detail',
    description:
      'Consignes d’exploitation formalisées : températures, horaires de ventilation, gestion des occultations en été. Sans investissement matériel, exige un suivi. Coût de mise en place.',
    fixedCost: 150,
    epSavingPct: 0.05,
    gesSavingPct: 0.05,
    dhReductionPct: 0.05,
    applicableWhen: '',
    requiresGestureIds: [],
    regulationRefs: ['decret_tertiaire', 'plan_canicule'],
  },
];
