import type { RenovationGesture } from '../types';

/** Danish renovation gestures — English UI names, DKK costs, refs into regulation-dk.ts. */
export const GESTURES_DK: RenovationGesture[] = [
  {
    id: 'dk-loftisolering',
    name: 'Loft and roof insulation',
    lot: 'toiture',
    mode: 'simple',
    description:
      'Increase insulation in the attic or roof (efterisolering af loft og tag) to reduce heat loss and improve summer comfort.',
    costPerM2: 900,
    epSavingPct: 0.16,
    gesSavingPct: 0.16,
    dhReductionPct: 0.1,
    applicableWhen: 'envelope.uRoof>0.25',
    requiresGestureIds: [],
    regulationRefs: ['br18', 'energirenoveringspuljen'],
  },
  {
    id: 'dk-facadeisolering',
    name: 'Facade insulation',
    lot: 'murs',
    mode: 'simple',
    description:
      'Insulate external walls when the facade is renewed; choose an assembly suitable for moisture-safe Danish construction.',
    costPerM2: 2200,
    epSavingPct: 0.14,
    gesSavingPct: 0.14,
    dhReductionPct: 0.08,
    applicableWhen: 'envelope.uWall>0.35',
    requiresGestureIds: [],
    regulationRefs: ['br18', 'energirenoveringspuljen'],
  },
  {
    id: 'dk-energiruder',
    name: 'Energy-efficient windows',
    lot: 'baies',
    mode: 'simple',
    description:
      'Replace single or ageing double glazing with low-emissivity energy windows (energiruder) and insulated frames.',
    costPerM2: 5200,
    epSavingPct: 0.1,
    gesSavingPct: 0.1,
    dhReductionPct: 0.06,
    applicableWhen: 'envelope.glazingType!=triple',
    requiresGestureIds: [],
    regulationRefs: ['br18'],
  },
  {
    id: 'dk-varmepumpe',
    name: 'Air-to-water heat pump',
    lot: 'chauffage',
    mode: 'simple',
    description:
      'Replace an oil or gas boiler with an efficient air-to-water heat pump (luft-til-vand-varmepumpe) where district heating is not available. Fixed installed package in DKK.',
    fixedCost: 115000,
    capacityPricing: false,
    epSavingPct: 0.32,
    gesSavingPct: 0.42,
    dhReductionPct: 0,
    applicableWhen: 'systems.heating.energy=gaz_naturel',
    requiresGestureIds: [],
    regulationRefs: ['varmepumpepuljen', 'klimaaftale'],
  },
  {
    id: 'dk-solafskaermning',
    name: 'External solar shading',
    lot: 'protections_solaires',
    mode: 'detail',
    description:
      'Fit exterior blinds, shutters or screens (solafskærmning) to reduce solar gains during increasingly warm summers.',
    fixedCost: 18000,
    epSavingPct: 0.01,
    gesSavingPct: 0.01,
    dhReductionPct: 0.3,
    applicableWhen: 'envelope.solarProtection=false',
    requiresGestureIds: [],
    regulationRefs: ['br18'],
  },
  {
    id: 'dk-solceller',
    name: 'Rooftop solar PV',
    lot: 'solaire',
    mode: 'simple',
    description:
      'Install photovoltaic panels (solceller) on an unobstructed roof and increase self-consumption where practical.',
    costPerM2: 1800,
    epSavingPct: 0.07,
    gesSavingPct: 0.05,
    dhReductionPct: 0,
    applicableWhen: 'systems.pvSurfaceM2<10',
    requiresGestureIds: [],
    regulationRefs: ['klimaaftale'],
  },
];
