/**
 * Renovation gesture database, Netherlands (branch `netherlands`).
 * Mode 'simple': macro gestures for the general public.
 * Mode 'detail': variants shown at audit level.
 *
 * Costs: indicative 2025 EUR, installation included. Where possible they
 * follow ISDE/SVV reference amounts and common Dutch market ranges:
 *   spouwmuurisolatie 20-35 €/m2, dakisolatie 40-70 €/m2,
 *   vloerisolatie 25-45 €/m2, HR++ glas 80-150 €/m2, triple glas 150-250 €/m2,
 *   gevelisolatie 90-140 €/m2, warmtepomp lucht-water 6000-12000 €,
 *   hybride warmtepomp 4000-7000 €, zonnepanelen 200-300 €/m2,
 *   zonneboiler 3000-5000 €, WTW ventilatie 3000-5500 €.
 * Figures not in this list are approximations pending verified pricing.
 * `applicableWhen` uses the shared DSL over Building paths.
 */

import type { RenovationGesture } from '../types';

export const GESTURES_NL: RenovationGesture[] = [
  // ------------------------------------------------------------------ walls
  {
    id: 'spouwmuurisolatie',
    name: 'Spouwmuurisolatie (cavity wall insulation)',
    lot: 'murs',
    mode: 'simple',
    description:
      'Injection of insulation granules or foam into the cavity of an uninsulated spouwmuur. The classic first Trias Energetica step for pre-1992 brick homes: cheap, fast, no visible change. Cost per m2 of wall (20-35 €/m2 range).',
    costPerM2: 27,
    epSavingPct: 0.15,
    gesSavingPct: 0.15,
    dhReductionPct: 0.04,
    applicableWhen: 'envelope.wallInsulation=aucune;envelope.wallMaterial=brique',
    requiresGestureIds: [],
    regulationRefs: ['isde', 'svn', 'trias_energetica', 'label_c_rental_2030'],
  },
  {
    id: 'gevelisolatie_buiten',
    name: 'Gevelisolatie buitenzijde (external wall insulation)',
    lot: 'murs',
    mode: 'simple',
    description:
      'Insulation boards on the outside of the facade under render or cladding, 12 to 18 cm. Used when there is no cavity or the facade needs renewal anyway. Cost per m2 of wall (90-140 €/m2 range).',
    costPerM2: 115,
    epSavingPct: 0.2,
    gesSavingPct: 0.2,
    dhReductionPct: 0.06,
    applicableWhen: 'envelope.wallInsulation=aucune',
    requiresGestureIds: [],
    regulationRefs: ['isde', 'svn', 'trias_energetica', 'label_c_rental_2030'],
  },
  {
    id: 'gevelisolatie_binnen',
    name: 'Gevelisolatie binnenzijde (internal wall insulation)',
    lot: 'murs',
    mode: 'detail',
    description:
      'Insulated lining on the inside of the facade, for monuments and facades that may not change outside. Loses a few centimeters of floor space per wall. Cost per m2 of wall (approximation pending verified pricing).',
    costPerM2: 75,
    epSavingPct: 0.15,
    gesSavingPct: 0.15,
    dhReductionPct: 0.03,
    applicableWhen: 'envelope.wallInsulation=aucune',
    requiresGestureIds: [],
    regulationRefs: ['isde', 'trias_energetica'],
  },

  // ------------------------------------------------------------------- roof
  {
    id: 'dakisolatie_hellend',
    name: 'Dakisolatie hellend dak (pitched roof insulation)',
    lot: 'toiture',
    mode: 'simple',
    description:
      'Insulation between or under the rafters of a pitched roof, 18 to 24 cm. Strong winter gain and it shields the top floor from summer heat. Cost per m2 of roof (40-70 €/m2 range).',
    costPerM2: 55,
    epSavingPct: 0.12,
    gesSavingPct: 0.12,
    dhReductionPct: 0.1,
    applicableWhen: 'envelope.roofType=inclinee',
    requiresGestureIds: [],
    regulationRefs: ['isde', 'svn', 'trias_energetica', 'label_c_rental_2030'],
  },
  {
    id: 'dakisolatie_plat',
    name: 'Dakisolatie plat dak (flat roof insulation)',
    lot: 'toiture',
    mode: 'simple',
    description:
      'Insulation on top of the flat roof under new roofing, standard with every roof renewal on portiekflats and galerijflats. Cuts top-floor overheating in summer. Cost per m2 of roof (40-70 €/m2 range).',
    costPerM2: 60,
    epSavingPct: 0.13,
    gesSavingPct: 0.13,
    dhReductionPct: 0.12,
    applicableWhen: 'envelope.roofType=terrasse',
    requiresGestureIds: [],
    regulationRefs: ['isde', 'svn', 'trias_energetica', 'label_c_rental_2030'],
  },
  {
    id: 'groen_dak',
    name: 'Groen dak (sedum green roof)',
    lot: 'toiture',
    mode: 'detail',
    description:
      'Extensive sedum layer on a flat roof. Buffers rainwater, protects the roofing and cools the top floor through evaporation. Needs a structural check. Cost per m2 of roof (approximation pending verified pricing).',
    costPerM2: 85,
    epSavingPct: 0.02,
    gesSavingPct: 0.02,
    dhReductionPct: 0.22,
    applicableWhen: 'envelope.roofType=terrasse',
    requiresGestureIds: [],
    regulationRefs: ['tojuli_nta8800'],
  },
  {
    id: 'wit_dak',
    name: 'Wit dak (high-reflectance cool roof)',
    lot: 'toiture',
    mode: 'detail',
    description:
      'White or highly reflective roofing that bounces sunlight instead of absorbing it. Direct TOjuli relief for the top floor, no winter benefit. Cost per m2 of roof (approximation pending verified pricing).',
    costPerM2: 38,
    epSavingPct: 0.02,
    gesSavingPct: 0.02,
    dhReductionPct: 0.18,
    applicableWhen: 'envelope.roofType=terrasse',
    requiresGestureIds: [],
    regulationRefs: ['tojuli_nta8800'],
  },

  // ------------------------------------------------------------------ floor
  {
    id: 'vloerisolatie',
    name: 'Vloerisolatie (floor insulation)',
    lot: 'plancher',
    mode: 'simple',
    description:
      'Insulation of the ground floor from the kruipruimte (crawl space) or from above. Removes cold-floor discomfort and cuts heat loss to the ground. Cost per m2 of floor (25-45 €/m2 range).',
    costPerM2: 35,
    epSavingPct: 0.08,
    gesSavingPct: 0.08,
    dhReductionPct: 0.02,
    applicableWhen: '',
    requiresGestureIds: [],
    regulationRefs: ['isde', 'svn', 'trias_energetica'],
  },
  {
    id: 'bodemisolatie',
    name: 'Bodemisolatie kruipruimte (crawl space floor insulation)',
    lot: 'plancher',
    mode: 'detail',
    description:
      'Insulation chips or foil on the soil of the crawl space. Cheaper than full floor insulation, slightly lower performance, often combined. Cost per m2 of floor (approximation pending verified pricing).',
    costPerM2: 20,
    epSavingPct: 0.05,
    gesSavingPct: 0.05,
    dhReductionPct: 0.01,
    applicableWhen: 'usage=residential_individual',
    requiresGestureIds: [],
    regulationRefs: ['isde', 'trias_energetica'],
  },

  // --------------------------------------------------------------- glazing
  {
    id: 'hrpp_glas',
    name: 'HR++ glas (high-efficiency double glazing)',
    lot: 'baies',
    mode: 'simple',
    description:
      'Replacement of single or old double glazing by HR++ glass, often in the existing frames. Standard ISDE measure with strong comfort gain near windows. Cost per m2 of glass (80-150 €/m2 range).',
    costPerM2: 115,
    epSavingPct: 0.1,
    gesSavingPct: 0.1,
    dhReductionPct: 0.04,
    applicableWhen: 'envelope.glazingType!=triple;envelope.glazingType!=double_renouvele',
    requiresGestureIds: [],
    regulationRefs: ['isde', 'svn', 'label_c_rental_2030'],
  },
  {
    id: 'triple_glas',
    name: 'Triple glas (triple glazing)',
    lot: 'baies',
    mode: 'detail',
    description:
      'Triple glazing on north and east facades, for deep renovation and BENG-level performance. Heavier frames, check the existing structure. Cost per m2 of glass (150-250 €/m2 range).',
    costPerM2: 200,
    epSavingPct: 0.12,
    gesSavingPct: 0.12,
    dhReductionPct: 0.04,
    applicableWhen: 'envelope.glazingType!=triple',
    requiresGestureIds: [],
    regulationRefs: ['isde', 'beng'],
  },
  {
    id: 'voorzetramen',
    name: 'Voorzetramen met HR glas (secondary glazing)',
    lot: 'baies',
    mode: 'detail',
    description:
      'A second inner window with HR glass behind monumental frames that may not be replaced. Monument-friendly route to near-double-glazing performance. Cost per m2 of glass (approximation pending verified pricing).',
    costPerM2: 140,
    epSavingPct: 0.08,
    gesSavingPct: 0.08,
    dhReductionPct: 0.03,
    applicableWhen: 'envelope.glazingType=simple;constructionYear<1946',
    requiresGestureIds: [],
    regulationRefs: ['isde', 'trias_energetica'],
  },

  // ------------------------------------------------------ shading (zonwering)
  {
    id: 'zonwering_buiten',
    name: 'Buitenzonwering (external screens and blinds)',
    lot: 'protections_solaires',
    mode: 'simple',
    description:
      'External screens, blinds or shutters on south, east and west windows. Blocks the sun before it hits the glass: the most effective TOjuli measure for the existing stock. Cost per m2 of glass (approximation pending verified pricing).',
    costPerM2: 250,
    epSavingPct: 0.03,
    gesSavingPct: 0.03,
    dhReductionPct: 0.28,
    applicableWhen: 'envelope.solarProtection=false',
    requiresGestureIds: [],
    regulationRefs: ['tojuli_nta8800', 'beng'],
  },
  {
    id: 'rolluiken',
    name: 'Rolluiken (roller shutters)',
    lot: 'protections_solaires',
    mode: 'detail',
    description:
      'Insulated roller shutters with timer control. Closed by day in summer they limit overheating; closed at night in winter they add thermal resistance. Cost per m2 of glass (approximation pending verified pricing).',
    costPerM2: 300,
    epSavingPct: 0.03,
    gesSavingPct: 0.03,
    dhReductionPct: 0.22,
    applicableWhen: 'envelope.solarProtection=false',
    requiresGestureIds: [],
    regulationRefs: ['tojuli_nta8800'],
  },
  {
    id: 'zonwerende_folie',
    name: 'Zonwerende folie (solar control film)',
    lot: 'protections_solaires',
    mode: 'detail',
    description:
      'Reflective film on exposed glazing. Quick and cheap, less effective than external shading, replace after about ten years. Cost per m2 of glass (approximation pending verified pricing).',
    costPerM2: 60,
    epSavingPct: 0.01,
    gesSavingPct: 0.01,
    dhReductionPct: 0.15,
    applicableWhen: 'envelope.solarProtection=false',
    requiresGestureIds: [],
    regulationRefs: ['tojuli_nta8800'],
  },

  // --------------------------------------------------------------- heating
  {
    id: 'warmtepomp_lucht_water',
    name: 'Warmtepomp lucht-water (air-to-water heat pump)',
    lot: 'chauffage',
    mode: 'simple',
    description:
      'Replacement of the CV-ketel by an all-electric air-to-water heat pump on the existing emitters. Cuts heating energy by half to two thirds and takes the home off gas. Fixed price installed (6000-12000 € range).',
    fixedCost: 9000,
    capacityPricing: false,
    epSavingPct: 0.5,
    gesSavingPct: 0.7,
    dhReductionPct: 0,
    applicableWhen: 'systems.heating.energy!=pac',
    requiresGestureIds: ['ltv_radiatoren'],
    regulationRefs: ['isde', 'svn', 'trias_energetica', 'label_c_rental_2030'],
  },
  {
    id: 'hybride_warmtepomp',
    name: 'Hybride warmtepomp (hybrid heat pump)',
    lot: 'chauffage',
    mode: 'simple',
    description:
      'A small heat pump next to the existing HR ketel: the heat pump covers most hours, the boiler only peaks and hot water. Lower cost entry off gas, common first step. Fixed price installed (4000-7000 € range).',
    fixedCost: 5500,
    capacityPricing: false,
    epSavingPct: 0.35,
    gesSavingPct: 0.45,
    dhReductionPct: 0,
    applicableWhen: 'systems.heating.energy=gaz_naturel',
    requiresGestureIds: [],
    regulationRefs: ['isde', 'trias_energetica'],
  },
  {
    id: 'ltv_radiatoren',
    name: 'LTV radiatoren (low-temperature emitters)',
    lot: 'chauffage',
    mode: 'detail',
    description:
      'Low-temperature radiators or fan convectors sized for 45 °C supply. Required for a heat pump to run efficiently on an existing system. Fixed price per dwelling (approximation pending verified pricing).',
    fixedCost: 3500,
    epSavingPct: 0.08,
    gesSavingPct: 0.08,
    dhReductionPct: 0,
    applicableWhen: '',
    requiresGestureIds: [],
    regulationRefs: ['trias_energetica'],
  },
  {
    id: 'hr_ketel_vervanging',
    name: 'HR ketel vervanging (condensing boiler replacement)',
    lot: 'chauffage',
    mode: 'detail',
    description:
      'Swap of an old conventional CV-ketel for a modern HR condensing boiler. Real but limited gain, keeps the home on gas; no longer the preferred subsidised route. Fixed price installed (approximation pending verified pricing).',
    fixedCost: 2800,
    epSavingPct: 0.1,
    gesSavingPct: 0.1,
    dhReductionPct: 0,
    applicableWhen: 'systems.heating.energy=gaz_naturel',
    requiresGestureIds: [],
    regulationRefs: ['beg_epbd'],
  },
  {
    id: 'aansluiting_stadsverwarming',
    name: 'Aansluiting stadsverwarming (district heating connection)',
    lot: 'chauffage',
    mode: 'detail',
    description:
      'Connection to the local heat network where available, replacing the boiler with a heat exchanger unit. Emissions depend on the network source mix. Fixed price with delivery set (approximation pending verified pricing).',
    fixedCost: 5000,
    epSavingPct: 0.15,
    gesSavingPct: 0.4,
    dhReductionPct: 0,
    applicableWhen: 'systems.heating.energy!=reseau_chaleur;usage!=residential_individual',
    requiresGestureIds: [],
    regulationRefs: ['trias_energetica', 'beg_epbd'],
  },
  {
    id: 'cv_inregelen',
    name: 'CV-installatie inregelen (hydronic balancing)',
    lot: 'chauffage',
    mode: 'detail',
    description:
      'Balancing the heating circuit, lowering the supply temperature to 60 °C and insulating pipes in unheated spaces. Small cost, immediate saving, precondition for a later heat pump. Fixed price (approximation pending verified pricing).',
    fixedCost: 600,
    epSavingPct: 0.05,
    gesSavingPct: 0.05,
    dhReductionPct: 0,
    applicableWhen: 'systems.heating.energy=gaz_naturel',
    requiresGestureIds: [],
    regulationRefs: ['trias_energetica'],
  },

  // ------------------------------------------------------------ hot water
  {
    id: 'warmtepompboiler',
    name: 'Warmtepompboiler (heat pump water heater)',
    lot: 'ecs',
    mode: 'simple',
    description:
      'Domestic hot water from a heat pump cylinder on extracted or outdoor air. Uses two to three times less energy than direct electric or boiler-fired hot water. Fixed price installed (approximation pending verified pricing).',
    fixedCost: 2800,
    epSavingPct: 0.07,
    gesSavingPct: 0.09,
    dhReductionPct: 0,
    applicableWhen: '',
    requiresGestureIds: [],
    regulationRefs: ['isde', 'trias_energetica'],
  },
  {
    id: 'zonneboiler',
    name: 'Zonneboiler (solar water heater)',
    lot: 'ecs',
    mode: 'detail',
    description:
      'Roof collectors with a double-coil cylinder covering 50 to 70 percent of annual hot water demand. ISDE subsidised. Fixed price installed (3000-5000 € range).',
    fixedCost: 4000,
    epSavingPct: 0.06,
    gesSavingPct: 0.08,
    dhReductionPct: 0,
    applicableWhen: 'usage=residential_individual',
    requiresGestureIds: [],
    regulationRefs: ['isde', 'trias_energetica'],
  },

  // --------------------------------------------------------------- cooling
  {
    id: 'plafondventilatoren',
    name: 'Plafondventilatoren (ceiling fans)',
    lot: 'refroidissement',
    mode: 'simple',
    description:
      'Ceiling fans in living rooms and bedrooms. Moving air improves perceived comfort by 2 to 3 °C for almost no electricity. Fixed price per dwelling or office floor (approximation pending verified pricing).',
    fixedCost: 600,
    epSavingPct: 0.01,
    gesSavingPct: 0.01,
    dhReductionPct: 0.2,
    applicableWhen: 'systems.hasCeilingFans=false',
    requiresGestureIds: [],
    regulationRefs: ['tojuli_nta8800'],
  },
  {
    id: 'nachtventilatie_unit',
    name: 'Nachtventilatie unit (mechanical night cooling)',
    lot: 'refroidissement',
    mode: 'detail',
    description:
      'A controlled ventilation unit that purges stored heat at night. Effective on medium and heavy construction. Fixed price with control (approximation pending verified pricing).',
    fixedCost: 2200,
    epSavingPct: 0.01,
    gesSavingPct: 0.01,
    dhReductionPct: 0.22,
    applicableWhen: 'systems.cooling=null;envelope.inertia!=legere',
    requiresGestureIds: [],
    regulationRefs: ['tojuli_nta8800'],
  },

  // ------------------------------------------------------------ ventilation
  {
    id: 'wtw_ventilatie',
    name: 'WTW ventilatie (balanced ventilation with heat recovery)',
    lot: 'ventilation',
    mode: 'simple',
    description:
      'Balanced mechanical ventilation with heat recovery (WTW). Recovers heat from extracted air, filters incoming air, and a summer bypass supports night purging. Fixed price installed (3000-5500 € range).',
    fixedCost: 4200,
    epSavingPct: 0.1,
    gesSavingPct: 0.1,
    dhReductionPct: 0.1,
    applicableWhen: 'systems.ventilation!=vmc_double_flux',
    requiresGestureIds: [],
    regulationRefs: ['isde', 'beng', 'trias_energetica'],
  },
  {
    id: 'mv_upgrade_co2',
    name: 'Mechanische ventilatie CO2-gestuurd (demand-controlled extract)',
    lot: 'ventilation',
    mode: 'detail',
    description:
      'Upgrade of the extract fan with CO2 and humidity sensors that modulate flow per room. Cuts ventilation losses without harming air quality. Fixed price installed (approximation pending verified pricing).',
    fixedCost: 1800,
    epSavingPct: 0.05,
    gesSavingPct: 0.05,
    dhReductionPct: 0.02,
    applicableWhen: 'systems.ventilation=naturelle',
    requiresGestureIds: [],
    regulationRefs: ['trias_energetica', 'beng'],
  },

  // ----------------------------------------------------------------- solar
  {
    id: 'zonnepanelen',
    name: 'Zonnepanelen (rooftop PV)',
    lot: 'solaire',
    mode: 'simple',
    description:
      'PV panels on the available roof, sized on daytime use and heat pump demand. Note the salderingsregeling is being phased out, which shifts value toward self-consumption. Cost per m2 of panel installed (200-300 €/m2 range).',
    costPerM2: 250,
    epSavingPct: 0.07,
    gesSavingPct: 0.05,
    dhReductionPct: 0,
    applicableWhen: 'systems.pvSurfaceM2<10',
    requiresGestureIds: [],
    regulationRefs: ['trias_energetica', 'beng'],
  },
  {
    id: 'zonnepanelen_uitbreiding',
    name: 'Zonnepanelen uitbreiding (PV extension)',
    lot: 'solaire',
    mode: 'detail',
    description:
      'Extra panels on the remaining roof surface with inverter resize. Cost per m2 of panel installed (approximation pending verified pricing).',
    costPerM2: 230,
    epSavingPct: 0.04,
    gesSavingPct: 0.03,
    dhReductionPct: 0,
    applicableWhen: 'systems.pvSurfaceM2>10',
    requiresGestureIds: [],
    regulationRefs: ['trias_energetica'],
  },

  // ----------------------------------------------------------------- usage
  {
    id: 'slimme_thermostaat',
    name: 'Slimme thermostaat en zoneregeling (smart thermostat)',
    lot: 'usage',
    mode: 'simple',
    description:
      'Programmable thermostat with per-room control: 19 °C in living spaces, setback at night and when away. Cheap measure with immediate payback. Fixed price (approximation pending verified pricing).',
    fixedCost: 350,
    epSavingPct: 0.08,
    gesSavingPct: 0.08,
    dhReductionPct: 0,
    applicableWhen: '',
    requiresGestureIds: [],
    regulationRefs: ['trias_energetica', 'label_c_rental_2030'],
  },
  {
    id: 'tochtstrips',
    name: 'Tochtstrips en kierdichting (draught proofing)',
    lot: 'usage',
    mode: 'detail',
    description:
      'Sealing strips and gap sealing around windows, doors and letterboxes. Stops draughts at the source for very little money. Fixed price per dwelling (approximation pending verified pricing).',
    fixedCost: 250,
    epSavingPct: 0.04,
    gesSavingPct: 0.04,
    dhReductionPct: 0.01,
    applicableWhen: '',
    requiresGestureIds: [],
    regulationRefs: ['trias_energetica'],
  },
  {
    id: 'radiatorfolie_ventilatoren',
    name: 'Radiatorfolie en radiatorventilatoren (radiator foil and fans)',
    lot: 'usage',
    mode: 'detail',
    description:
      'Reflective foil behind radiators on outer walls plus small fans under the convectors that spread heat at lower water temperature. DIY-level cost. Fixed price (approximation pending verified pricing).',
    fixedCost: 180,
    epSavingPct: 0.03,
    gesSavingPct: 0.03,
    dhReductionPct: 0,
    applicableWhen: 'systems.heating.energy=gaz_naturel',
    requiresGestureIds: [],
    regulationRefs: ['trias_energetica'],
  },
  {
    id: 'gedragsmaatregelen',
    name: 'Gedragsmaatregelen (behaviour and setpoints charter)',
    lot: 'usage',
    mode: 'detail',
    description:
      'Agreed setpoints and habits: 19 °C living areas, shorter showers, laundry at lower temperature, closed blinds on hot days. No hardware, needs follow-up. Setup cost (approximation pending verified pricing).',
    fixedCost: 100,
    epSavingPct: 0.05,
    gesSavingPct: 0.05,
    dhReductionPct: 0.05,
    applicableWhen: '',
    requiresGestureIds: [],
    regulationRefs: ['trias_energetica', 'label_c_rental_2030'],
  },
];
